const express=require("express"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const app=express(),PORT=process.env.PORT||3000,ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"123456",ADMIN_TOKEN=crypto.createHash("sha256").update(ADMIN_PASSWORD).digest("hex"),ordersPath=path.join(__dirname,"orders.json");
app.use(express.json({limit:"1mb"}));app.use(express.static(path.join(__dirname,"public")));
function read(){if(!fs.existsSync(ordersPath))return[];try{return JSON.parse(fs.readFileSync(ordersPath,"utf-8"))}catch{return[]}}
function save(o){fs.writeFileSync(ordersPath,JSON.stringify(o,null,2),"utf-8")}
function now(){return new Date().toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"})}
function orderNo(){let d=new Date(),p=n=>String(n).padStart(2,"0"),t=`${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`,r=Math.floor(Math.random()*900+100);return`XC${t}${r}`}
function key(){return crypto.randomBytes(16).toString("hex")}
function deposit(s){if(s==="Word排版")return"3";if(["学习计划网页","网页二维码制作","其他需求"].includes(s))return"9.9";return"5"}
function balance(o){let price=parseFloat(o.price)||0,dep=parseFloat(o.deposit)||0;return price>dep?(price-dep).toFixed(1):""}
function admin(req,res,next){let token=(req.headers.authorization||"").replace("Bearer ","");if(token!==ADMIN_TOKEN)return res.status(401).json({success:false,message:"未登录或密码错误"});next()}
function pub(o,withKey=false){let data={orderNo:o.orderNo||String(o.id),name:o.name,email:o.email||"",service:o.service,deadline:o.deadline,style:o.style||"",details:o.details,status:o.status||"pending_payment",price:o.price||"",deposit:o.deposit||"",balanceDue:balance(o),publicNote:o.publicNote||"",paymentNote:o.paymentNote||"",balancePaymentNote:o.balancePaymentNote||"",deliveryLink:o.deliveryLink||"",deliveryNote:o.deliveryNote||"",createdAt:o.createdAt||"",updatedAt:o.updatedAt||"",trackPath:`/track/${encodeURIComponent(o.orderNo||String(o.id))}?key=${encodeURIComponent(o.trackKey||"")}`};if(withKey)data.trackKey=o.trackKey||"";return data}
app.get("/admin",(req,res)=>res.sendFile(path.join(__dirname,"public","admin.html")));
app.get("/track",(req,res)=>res.sendFile(path.join(__dirname,"public","track.html")));
app.get("/track/:orderNo",(req,res)=>res.sendFile(path.join(__dirname,"public","track.html")));
app.post("/api/orders",(req,res)=>{let{name,contact,email,service,deadline,style,details}=req.body;if(!name||!contact||!service||!details)return res.status(400).json({success:false,message:"缺少必填信息"});let orders=read(),no=orderNo(),tk=key(),o={id:Date.now(),orderNo:no,trackKey:tk,name:String(name).trim(),contact:String(contact).trim(),email:String(email||"").trim(),service:String(service).trim(),deadline:deadline?String(deadline).trim():"未填写",style:String(style||"").trim(),details:String(details).trim(),status:"pending_payment",deposit:deposit(String(service).trim()),price:"",note:"",publicNote:"订单已生成，请先支付定金。付款后填写付款备注，我确认后会开始处理。",paymentNote:"",balancePaymentNote:"",deliveryLink:"",deliveryNote:"",createdAt:now(),updatedAt:""};orders.unshift(o);save(orders);res.json({success:true,message:"提交成功",order:pub(o,true)})});
app.get("/api/track/:orderNo",(req,res)=>{let o=read().find(x=>String(x.orderNo||x.id)===String(req.params.orderNo)&&String(x.trackKey||"")===String(req.query.key||""));if(!o)return res.status(404).json({success:false,message:"订单链接无效或已失效"});res.json({success:true,order:pub(o,true)})});
app.post("/api/track",(req,res)=>{let{orderNo,contact}=req.body;if(!orderNo||!contact)return res.status(400).json({success:false,message:"请填写订单号和联系方式"});let o=read().find(x=>String(x.orderNo||x.id).trim().toLowerCase()===String(orderNo).trim().toLowerCase()&&String(x.contact||"").trim().toLowerCase()===String(contact).trim().toLowerCase());if(!o)return res.status(404).json({success:false,message:"未查询到订单"});res.json({success:true,order:pub(o,true)})});
app.post("/api/payment-note/:orderNo",(req,res)=>{let{key,paymentNote}=req.body;if(!paymentNote)return res.status(400).json({success:false,message:"请填写付款备注"});let orders=read(),o=orders.find(x=>String(x.orderNo||x.id)===String(req.params.orderNo)&&String(x.trackKey||"")===String(key||""));if(!o)return res.status(404).json({success:false,message:"订单链接无效"});o.paymentNote=String(paymentNote).trim();o.status="payment_review";o.publicNote="已收到定金付款备注，正在确认。确认后会更新进度。";o.updatedAt=now();save(orders);res.json({success:true,order:pub(o,true)})});
app.post("/api/balance-note/:orderNo",(req,res)=>{let{key,balancePaymentNote}=req.body;if(!balancePaymentNote)return res.status(400).json({success:false,message:"请填写尾款付款备注"});let orders=read(),o=orders.find(x=>String(x.orderNo||x.id)===String(req.params.orderNo)&&String(x.trackKey||"")===String(key||""));if(!o)return res.status(404).json({success:false,message:"订单链接无效"});o.balancePaymentNote=String(balancePaymentNote).trim();o.status="final_payment_review";o.publicNote="已收到尾款付款备注，正在确认。确认后会移交文件。";o.updatedAt=now();save(orders);res.json({success:true,order:pub(o,true)})});
app.get("/api/orders",(req,res)=>res.json(read().map(o=>pub(o))));
app.post("/api/admin/login",(req,res)=>{if(req.body.password===ADMIN_PASSWORD)return res.json({success:true,token:ADMIN_TOKEN});res.status(401).json({success:false,message:"后台密码错误"})});
app.get("/api/admin/orders",admin,(req,res)=>res.json(read()));
app.patch("/api/admin/orders/:id",admin,(req,res)=>{let orders=read(),o=orders.find(x=>x.id===Number(req.params.id));if(!o)return res.status(404).json({success:false,message:"未找到订单"});let allowed=["pending_payment","payment_review","deposit_paid","doing","final_payment_due","final_payment_review","balance_paid","delivered","done","cancel"];let fields=["name","contact","email","service","deadline","style","details","status","price","deposit","note","publicNote","paymentNote","balancePaymentNote","deliveryLink","deliveryNote"];for(let f of fields)if(req.body[f]!==undefined){if(f==="status"&&!allowed.includes(req.body[f]))return res.status(400).json({success:false,message:"状态不正确"});o[f]=String(req.body[f]).trim()}o.updatedAt=now();save(orders);res.json({success:true,order:o})});
app.delete("/api/admin/orders/:id",admin,(req,res)=>{let orders=read(),next=orders.filter(x=>x.id!==Number(req.params.id));if(next.length===orders.length)return res.status(404).json({success:false,message:"未找到订单"});save(next);res.json({success:true})});

const contentPath=path.join(__dirname,"siteContent.json");
function readContent(){if(!fs.existsSync(contentPath))return {services:[],examples:[],pricing:[],pricingNote:""};try{return JSON.parse(fs.readFileSync(contentPath,"utf-8"))}catch{return {services:[],examples:[],pricing:[],pricingNote:""}}}
function saveContent(d){fs.writeFileSync(contentPath,JSON.stringify(d,null,2),"utf-8")}
app.get("/admin-content",(req,res)=>res.sendFile(path.join(__dirname,"public","admin-content.html")));
app.get("/api/site-content",(req,res)=>res.json(readContent()));
app.get("/api/admin/site-content",admin,(req,res)=>res.json(readContent()));
app.patch("/api/admin/site-content",admin,(req,res)=>{saveContent(req.body);res.json({success:true})});

app.listen(PORT,"0.0.0.0",()=>console.log("caistudio running on "+PORT));
